#!/bin/sh

# author name
author=$(git config --global --get user.name);

#modified date of files
moddate=$(date -r $file +"%x %X");

#files added
#addedfiles=$(git diff --cached --name-only);
addedfiles=$(git status --porcelain | awk 'match($1, "A"){print $2}');

#files modified
#modifiedfiles=$(git diff --name-only);
modifiedfiles=$(git status --porcelain | awk 'match($1, "M"){print $2}');

#all the files together with their relative paths
files="$addedfiles $modifiedfiles";
#regex author keyword we looking for %Author%
reg_author='%Author[^%]*%';

#regex Date keyword we looking for %Date%
reg_date='%Date[^%]*%';

#echo $author;
#echo $moddate;
#echo $files;

#for every file in the files variable find the %Author% and %Date% keywords and replace them
#with the author who modified them and the date it was modified.
for file in $files; do
    sed  -i -e "s#$reg_author#%Author: $author %#;s#$reg_date#%Date: $moddate %#" $file                                                 
done


